spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/appjam?serverTimezone=UTC&characterEncoding=UTF-8}
    username: ${DB_USER:cos}
    password: ${DB_PWD:cos1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    port: ${REDIS_PORT:6379}
    host: ${REDIS_HOST:localhost}

jwt:
  header: ${JWT_HEADER:Authorization}
  prefix: ${JWT_PREFIX:Bearer}
  secretKey: ${JWT_SECRET_KEY:secret}
  accessExp: ${JWT_ACCESS_EXP:3600}
  refreshExp: ${JWT_REFRESH_EXP:3600}

cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESSKEY:AKIARPJSAODFWRB4BPXG}
      secretKey: ${S3_SECRETKEY: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}
    s3:
      bucket: ${S3_BUCKET:appjam-s3}
    region:
      static: ${ap-northeast-2
    stack:
      auto: false

